name: Simple CI/CD Pipeline

on:
  push:
    branches: [main]

env:
  DOCKER_REGISTRY: gcr.io/${{ secrets.GCP_PROJECT }}   # Replace with ACR if needed
  K8S_NAMESPACE: dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # -------------------------
      # Build Node.js services
      # -------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build Patient Service
        working-directory: ./patient-service
        run: |
          npm install
          npm test

      - name: Build Appointment Service
        working-directory: ./appointment-service
        run: |
          npm install
          npm test

      # -------------------------
      # Build Java service
      # -------------------------
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Order Service
        working-directory: ./order-service
        run: |
          ./mvnw clean install

      # -------------------------
      # Build & Push Docker Images
      # -------------------------
      - name: Authenticate GCP Docker
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | gcloud auth activate-service-account --key-file=-
          gcloud auth configure-docker

      - name: Docker Build & Push Patient Service
        run: |
          docker build -t $DOCKER_REGISTRY/patient-service:latest ./patient-service
          docker push $DOCKER_REGISTRY/patient-service:latest

      - name: Docker Build & Push Appointment Service
        run: |
          docker build -t $DOCKER_REGISTRY/appointment-service:latest ./appointment-service
          docker push $DOCKER_REGISTRY/appointment-service:latest

      - name: Docker Build & Push Order Service
        run: |
          docker build -t $DOCKER_REGISTRY/order-service:latest ./order-service
          docker push $DOCKER_REGISTRY/order-service:latest

      # -------------------------
      # Deploy to Kubernetes via Helm
      # -------------------------
      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Deploy Patient Service
        run: |
          helm upgrade --install patient-service ./charts/patient-service \
            --namespace $K8S_NAMESPACE \
            --set image.repository=$DOCKER_REGISTRY/patient-service \
            --set image.tag=latest

      - name: Deploy Appointment Service
        run: |
          helm upgrade --install appointment-service ./charts/appointment-service \
            --namespace $K8S_NAMESPACE \
            --set image.repository=$DOCKER_REGISTRY/appointment-service \
            --set image.tag=latest

      - name: Deploy Order Service
        run: |
          helm upgrade --install order-service ./charts/order-service \
            --namespace $K8S_NAMESPACE \
            --set image.repository=$DOCKER_REGISTRY/order-service \
            --set image.tag=latest
